/*
**
** File: cf_external_functions.h
** This file is automatically generated by the
** chain flow assembler
** Build Time: 2016-09-22 10:54:19.869000  
**
*/

#ifndef _EXTERNAL_FUNCTIONS_H_
#define _EXTERNAL_FUNCTIONS_H_ 

#include <device.h>
#include "cf_chain_flow_support.h" 
#include "cf_events.h"
/*
This is the symbolic definitions of the chains
*/



#define  initialization   0
#define  measure_die_temperature   1
#define  process_rtu_packet   2
#define  second_tick_chain   3
#define  minute_tick_chain   4
#define  soil_measurement_calibration   5
#define  sequence_moisture_measurement   6
#define  measure_channel   7
#define  hour_tick_chain   8
#define  commissioning_heart_beat   9
#define  heart_beat   10
#define  handle_commissioning   11



/*
This is the symbolic definitions of the links for chain initialization
*/
#define  initialization_0   0
#define  initialization_1   1
#define  initialization_2   2
#define  initialization_3   3
#define  initialization_4   4
#define  initialization_5   5
#define  initialization_6   6
#define  initialization_7   7
#define  initialization_8   8
#define  initialization_9   9
#define  initialization_10   10
#define  initialization_11   11
#define  initialization_12   12
#define  initialization_13   13
#define  initialization_14   14



/*
This is the symbolic definitions of the links for chain measure_die_temperature
*/
#define  measure_die_temperature_0   0
#define  measure_die_temperature_1   1
#define  measure_die_temperature_2   2



/*
This is the symbolic definitions of the links for chain process_rtu_packet
*/
#define  process_rtu_packet_0   0
#define  process_rtu_packet_1   1
#define  process_rtu_packet_2   2



/*
This is the symbolic definitions of the links for chain second_tick_chain
*/
#define  second_tick_chain_0   0
#define  second_tick_chain_1   1
#define  second_tick_chain_2   2
#define  second_tick_chain_3   3
#define  second_tick_chain_4   4
#define  second_tick_chain_5   5
#define  second_tick_chain_6   6
#define  second_tick_chain_7   7



/*
This is the symbolic definitions of the links for chain minute_tick_chain
*/
#define  minute_tick_chain_0   0
#define  minute_tick_chain_1   1
#define  minute_tick_chain_2   2
#define  minute_tick_chain_3   3



/*
This is the symbolic definitions of the links for chain soil_measurement_calibration
*/
#define  soil_measurement_calibration_0   0
#define  soil_measurement_calibration_1   1
#define  soil_measurement_calibration_2   2
#define  soil_measurement_calibration_3   3
#define  soil_measurement_calibration_4   4
#define  soil_measurement_calibration_5   5



/*
This is the symbolic definitions of the links for chain sequence_moisture_measurement
*/
#define  sequence_moisture_measurement_0   0
#define  sequence_moisture_measurement_1   1
#define  sequence_moisture_measurement_2   2
#define  sequence_moisture_measurement_3   3
#define  sequence_moisture_measurement_4   4
#define  sequence_moisture_measurement_5   5
#define  sequence_moisture_measurement_6   6
#define  sequence_moisture_measurement_7   7
#define  sequence_moisture_measurement_8   8
#define  sequence_moisture_measurement_9   9
#define  sequence_moisture_measurement_10   10
#define  sequence_moisture_measurement_11   11
#define  sequence_moisture_measurement_12   12
#define  sequence_moisture_measurement_13   13
#define  sequence_moisture_measurement_14   14
#define  sequence_moisture_measurement_15   15
#define  sequence_moisture_measurement_16   16
#define  sequence_moisture_measurement_17   17
#define  sequence_moisture_measurement_18   18



/*
This is the symbolic definitions of the links for chain measure_channel
*/
#define  measure_channel_0   0
#define  measure_channel_1   1
#define  measure_channel_2   2
#define  measure_channel_3   3
#define  measure_channel_4   4
#define  measure_channel_5   5
#define  measure_channel_6   6
#define  measure_channel_7   7
#define  measure_channel_8   8
#define  measure_channel_9   9
#define  measure_channel_10   10
#define  measure_channel_11   11
#define  measure_channel_12   12
#define  measure_channel_13   13
#define  measure_channel_14   14



/*
This is the symbolic definitions of the links for chain hour_tick_chain
*/
#define  hour_tick_chain_0   0
#define  hour_tick_chain_1   1



/*
This is the symbolic definitions of the links for chain commissioning_heart_beat
*/
#define  commissioning_heart_beat_0   0
#define  commissioning_heart_beat_1   1
#define  commissioning_heart_beat_2   2
#define  commissioning_heart_beat_3   3



/*
This is the symbolic definitions of the links for chain heart_beat
*/
#define  heart_beat_0   0
#define  heart_beat_1   1
#define  heart_beat_2   2
#define  heart_beat_3   3



/*
This is the symbolic definitions of the links for chain handle_commissioning
*/
#define  handle_commissioning_0   0
#define  handle_commissioning_1   1
#define  handle_commissioning_2   2
#define  handle_commissioning_3   3
#define  handle_commissioning_4   4
#define  handle_commissioning_5   5
#define  handle_commissioning_6   6
#define  handle_commissioning_7   7
#define  handle_commissioning_8   8
#define  handle_commissioning_9   9
#define  handle_commissioning_10   10
#define  handle_commissioning_11   11



int make_source_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int update_soil_temperature_second(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int enable_eeprom(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int update_modbus_rtc_values(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int process_rtu_message(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int store_moisture_data(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int  toggle_heart_beat(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int enable_interrupts(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_modbus_watch_dog_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int meaure_die_temperature(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_source_channel(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int initialize_die_temp_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int check_logging_active_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int remove_power(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_modbus_reset_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int check_for_moisture_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int initialize_controller_wd_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int check_moisture_active_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int switch_on_fn(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int init_event_queue(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int clear_reset_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int init_vdac(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int init_rtc(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int switch_off_fn(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_sink_channel(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int store_calibration_result(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_normal_modbus_address(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int pat_watch_dog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int setup_measurement_channel(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int start_watchdog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int initialize_callibration_variables(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int enable_timer_interrupt(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int make_sink_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int update_soil_temperature_minute(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int initialize_modbus_rtu(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int init_idac(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_commissiong_address(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);






#endif
