/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* This file provides basic startup and mux configration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */
extern void SetAnalogRoutingPumps(uint8 enabled);
extern void Sink_Source_Setup_Set(uint8 channel);
extern void Sink_Source_Setup_Unset(uint8 channel);
/* Sink_Source_Setup__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE Sink_Source_Setup__addrTable[34];
/* Sink_Source_Setup__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE Sink_Source_Setup__maskTable[34];
extern void SIGMA_A_D_AMux_Set(uint8 channel);
extern void SIGMA_A_D_AMux_Unset(uint8 channel);
/* SIGMA_A_D_AMux__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE SIGMA_A_D_AMux__addrTable[2];
/* SIGMA_A_D_AMux__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE SIGMA_A_D_AMux__maskTable[2];


#endif /* CYFITTER_CFG_H */

/*[]*/
