/*
** File: usb_serial.h
** Public prototypes are defined in cf_external_functions.h
** the public prototypes are generated by chain flow assembler
**
*/

#ifndef _USB_SERIAL_H_
#define _USB_SERIAL_H_

#define MODBUS_PACKET_SIZE 256
    
#endif